# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Psychology @ Occam
email: info@occameducation.com
description: > # this means to ignore newlines until "baseurl:"
  Psychology resources for educators brought to you by Occam Education
baseurl: "" # the subpath of your site, e.g. /blog
url: psych.occameducation.com # the base hostname & protocol for your site
copyright: Material herein can only be legally licensed, reproduced, distributed or in any other way used with direct, written permission from Occam Education, LLC.

# Build settings
markdown: kramdown
